---
# LAB 6: Feature Extraction and Selection
### One-Hot Encoding, Label Encoding, Frequency Encoding, PCA, RFE

### Encoding Categorical Variables

In [2]:
import pandas as pd
import numpy as np

data = {'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']}
df = pd.DataFrame(data)

# One-Hot Encoding
encoded_df = pd.get_dummies(df, columns=['Color'], drop_first=False)
print("One-Hot Encoded:\n", encoded_df)

# Label Encoding
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Color_Label'] = label_encoder.fit_transform(df['Color'])
print("\nLabel Encoded:\n", df)

# Frequency Encoding
frequency_map = df['Color'].value_counts().to_dict()
df['Color_Frequency'] = df['Color'].map(frequency_map)
print("\nFrequency Encoded:\n", df)

One-Hot Encoded:
    Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3        True        False      False
4       False        False       True

Label Encoded:
    Color  Color_Label
0    Red            2
1   Blue            0
2  Green            1
3   Blue            0
4    Red            2

Frequency Encoded:
    Color  Color_Label  Color_Frequency
0    Red            2                2
1   Blue            0                2
2  Green            1                1
3   Blue            0                2
4    Red            2                2


### Polynomial Features & Rolling Statistics

In [3]:
from sklearn.preprocessing import PolynomialFeatures

df['Feature1'] = np.random.rand(len(df))
df['Feature2'] = np.random.rand(len(df))

poly = PolynomialFeatures(degree=2, interaction_only=False, include_bias=False)
poly_features = poly.fit_transform(df[['Feature1', 'Feature2']])
print("Polynomial Features:\n", poly_features)

df['Value'] = np.random.rand(len(df))
df['Rolling_Mean'] = df['Value'].rolling(window=3).mean()
df['Rolling_Std'] = df['Value'].rolling(window=3).std()
print("\nWith Rolling Stats:\n", df)

Polynomial Features:
 [[0.95501004 0.72352458 0.91204418 0.69097324 0.52348782]
 [0.19961525 0.94201591 0.03984625 0.18804074 0.88739398]
 [0.59351328 0.23196227 0.35225801 0.13767269 0.05380649]
 [0.03687281 0.34238002 0.0013596  0.01262451 0.11722408]
 [0.26186267 0.4565623  0.06857206 0.11955662 0.20844913]]

With Rolling Stats:
    Color  Color_Label  Color_Frequency  Feature1  Feature2     Value  \
0    Red            2                2  0.955010  0.723525  0.587942   
1   Blue            0                2  0.199615  0.942016  0.439412   
2  Green            1                1  0.593513  0.231962  0.426422   
3   Blue            0                2  0.036873  0.342380  0.370480   
4    Red            2                2  0.261863  0.456562  0.771830   

   Rolling_Mean  Rolling_Std  
0           NaN          NaN  
1           NaN          NaN  
2      0.484592     0.089739  
3      0.412105     0.036629  
4      0.522911     0.217378  


### Feature Selection — Correlation, SelectKBest, RFE

In [ ]:
from sklearn.feature_selection import f_regression, SelectKBest
from sklearn.impute import SimpleImputer

df['Target'] = np.random.rand(len(df))
numerical_df = df.select_dtypes(include=np.number)
correlation = numerical_df.corr()
print("Correlation with Feature1:\n", correlation['Feature1'])

X = df.drop(columns=['Target', 'Color']).dropna()
y = df['Target'][X.index]
X_new = SelectKBest(f_regression, k=5).fit_transform(X, y)
print("\nSelectKBest output:\n", X_new)

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

model = LinearRegression()
rfe = RFE(model, n_features_to_select=5)
X_rfe = rfe.fit_transform(X, y)
print("RFE Selected Features:", rfe.support_)

### PCA (Principal Component Analysis)